# Copyright 2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

CRATES=""

RUST_MIN_VER="1.88.0"

inherit cargo git-r3

DESCRIPTION="Embedded scheme interpreter in Rust"
HOMEPAGE="https://github.com/mattwparas/steel"

EGIT_REPO_URI="https://github.com/mattwparas/steel"

LICENSE="|| ( MIT Apache-2.0 )"
# Dependent crate licenses (generated by pycargoebuild 0.15.3)
LICENSE+="
	Apache-2.0 Apache-2.0-with-LLVM-exceptions BSD Boost-1.0
	CDLA-Permissive-2.0 ISC MIT MPL-2.0 openssl Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

# The test suite requires building the entire workspace, including the
# native dylib packages under libs/.
RESTRICT="test"

# steel-forge vendors openssl and libgit2 (git2 with vendored-openssl)
BDEPEND="
	dev-lang/perl
	virtual/pkgconfig
"
DEPEND="virtual/zlib"
RDEPEND="${DEPEND}"

QA_FLAGS_IGNORED="usr/bin/.*"

src_unpack() {
	git-r3_src_unpack
	cargo_live_src_unpack
}

src_prepare() {
	default
	# hardcoded aarch64 cross linker
	rm .cargo/config.toml || die
}

src_compile() {
	local packages=(
		steel-interpreter
		cargo-steel-lib
		steel-language-server
		steel-forge
	)
	cargo_src_compile "${packages[@]/#/--package=}"
}

src_install() {
	local target
	target="$(cargo_target_dir)"
	dobin "${target}"/{steel,forge,cargo-steel-lib,steel-language-server}

	# Install the cogs (steel's scheme libraries) system-wide using the
	# freshly built interpreter, mirroring upstream's nix package.
	local steel_home="${ED}/usr/share/steel"
	dodir /usr/share/steel
	pushd cogs >/dev/null || die
	STEEL_HOME="${steel_home}" "${S}/${target}/steel" install.scm \
		|| die "cog installation failed"
	popd >/dev/null || die

	# Scripts generated by the cog installer (repl-connect)
	if [[ -d ${steel_home}/bin ]]; then
		dobin "${steel_home}"/bin/*
		rm -r "${steel_home}/bin" || die
	fi

	einstalldocs
}

pkg_postinst() {
	einfo "Steel looks for cogs in STEEL_HOME, which defaults to the"
	einfo "user-writable ~/.local/share/steel. Seed it once with the"
	einfo "packaged cogs:"
	einfo "  cp -r ${EROOT}/usr/share/steel/cogs ~/.local/share/steel/"
	einfo "Alternatively, set STEEL_HOME=${EROOT}/usr/share/steel for a"
	einfo "read-only, system-managed setup."
}
